source "http://rubygems.org"

gem "bundler", ">= 1.0.14"
gem "rake", ">= 0.9.2"

# development path manually added, this is here just for dependencies
gem "win32-autogui", ">= 0.5.0"

# scripting
gem "mutagem", ">= 0.2.0"

# this gem is only used if ANSICON support is not detected
gem "win32console", ">= 1.2.0"

# Specs and Features
gem "rspec", ">= 2.6.0"
gem "cucumber", "~> 1.0"
gem "aruba", "~> 0.4.2"
